# Transcribed verbatim from MCP twmd.describe_dataset (one call per dataset), 2026-08-12.
# tuple = (name_zh, category, tier, route_slug, knowledge_time_field, point_in_time_safe, has_pit_note, grain)
PIT = {
"balance_sheet":("財報-資產負債表","fundamental","pro","balance-sheet","disclosure_date",False,False,"ticker|fiscal_year|fiscal_quarter"),
"income_statement":("財報-損益表","fundamental","pro","income-statement","observed_available_date",False,True,"ticker|fiscal_year|fiscal_quarter"),
"cash_flow_statement":("財報-現金流量表","fundamental","pro","cash-flow-statement","disclosure_date",False,False,"ticker|fiscal_year|fiscal_quarter"),
"financial_ratios":("財務比率","fundamental_derived","pro","financial-metrics","observed_available_date",False,True,"ticker|fiscal_year|fiscal_quarter"),
"monthly_revenue":("月營收","fundamental","free","monthly-revenue","as_of_date",False,True,"ticker|revenue_month"),
"valuation_data":("估值 PER/PBR/殖利率","fundamental","free","valuation-data","trade_date",True,False,"ticker|trade_date|market"),
"valuation_core_daily":("Valuation Core Daily","","pro","valuation-core-daily","date",True,False,""),
"twse_daily_price":("TWSE Daily Price","","free","twse-daily-price","trade_date",True,False,""),
"tpex_daily_price":("TPEx Daily Price","","free","tpex-daily-price","trade_date",True,False,""),
"price_enhanced":("Price Adjustment Factors (價格調整因子)","","starter","price-enhanced",None,True,False,""),
"return_index_daily":("報酬指數(含息)","price","pro","return-index-daily","trade_date",True,False,"index_code|trade_date"),
"market_index":("大盤/類股指數日線","price","free","market-index","trade_date",True,False,"index_code|trade_date"),
"industry_index":("產業別指數日線","price","free","index-classification","trade_date",True,False,"industry_name|trade_date|market"),
"industry_index_daily":("Industry Index Daily","","starter","industry-index-daily","date",True,False,""),
"index_constituents":("Index Constituents (指數成分股)","","free","index-constituents","trade_date",True,False,""),
"market_value_weight":("個股市值權重","price","pro","market-value-weight","as_of_date",True,False,"ticker|as_of_date"),
"market_breadth":("Market Breadth","","starter","market-breadth","as_of_date",True,False,""),
"market_overview_snapshots":("Market Overview Snapshots","","developer","market-overview-snapshots","as_of_date",True,False,""),
"technical_indicators":("技術指標","derived","max","technical-indicators","trade_date",True,True,"ticker|trade_date|market|indicator_basis"),
"limit_events":("漲跌停事件","price","starter","limit-events","trade_date",True,False,"symbol|trade_date|direction"),
"price_move_context":("大波動日情境卡","price","starter","price-move-context","trade_date",True,False,"symbol|trade_date|market"),
"stock_price_limit_daily":("Stock Price Limit Daily (每日漲跌停價位)","","max","stock-price-limit-daily","trade_date",True,False,""),
"institutional_flow":("三大法人買賣超(合計)","chip","starter","institutional-flow","trade_date",True,False,"ticker|trade_date|market"),
"margin_short":("融資融券餘額","chip","starter","margin-short","trade_date",True,False,"ticker|trade_date|market"),
"margin_short_total":("Margin Short Total","","starter","total-margin-short",None,True,False,""),
"margin_system_stats":("信用交易系統統計","chip","pro","margin-system-stats","trade_date",True,False,"market|trade_date"),
"securities_lending":("借券/借券賣出","chip","starter","securities-lending","trade_date",True,False,"ticker|trade_date"),
"lending_utilization":("借券使用率","chip","max","lending-utilization","trade_date",True,False,"ticker|market|trade_date"),
"short_sale_balance_control":("平盤下融券借券管控","chip","max","short-sale-balance-control","trade_date",True,False,"ticker|trade_date"),
"short_restriction_flags":("空方限制旗標","chip","max","short-restriction-flags","trade_date",True,False,"ticker|market|trade_date"),
"foreign_holding":("外資持股比率","chip","pro","foreign-holding","trade_date",True,False,"ticker|trade_date"),
"shareholding_concentration":("集保持股分級集中度","chip","starter","shareholding-concentration","report_date",True,True,"ticker|market|report_date"),
"block_trade_daily":("Block Trade Daily","","developer","block-trade-daily","trade_date",True,False,""),
"security_master":("證券主檔","dimension","free","security-master","as_of_date",True,False,"ticker"),
"trading_calendar":("交易日曆","dimension","free","trading-calendar","trade_date",True,True,"trade_date|market"),
"securities_firm_master":("證券商總表","relation","free","securities-firm-master","report_date",True,False,"broker_id"),
"broker_branch_reference":("券商分點名冊","reference","free","broker-branch-reference","snapshot_date",True,True,""),
"issuer_classification":("Issuer Classification","","free","issuer-classification","as_of_date",True,False,""),
"issuer_profiles":("Issuer Profiles","","free","issuer-profile","source_as_of",True,False,""),
"fund_etf_metadata":("Fund / ETF Metadata (基金·ETF 基本資料)","","free","fund-etf-metadata","source_as_of_date",True,False,""),
"etf_holdings":("ETF Holdings (ETF 成分持股)","","developer","etf-holdings","as_of_date",True,False,""),
"warrants_reference":("權證參考資料","reference","free","warrants-reference","listing_date",True,True,""),
"bond_convertible_reference":("可轉債參考主檔","reference","free","bond-convertible-reference","issue_date",True,True,""),
"trading_rules_reference":("交易制度沿革表","rag_text","free","trading-rules-reference","effective_date",True,True,"rule_domain|rule_key|effective_date"),
"tax_business_registration":("Business Registration (商業登記)","","developer","tax-business-registration","source_as_of_date",True,False,""),
"governance_t187ap33_l":("Governance Chairman/GM Duality (t187ap33_L)","","developer","governance-t187ap33-l","as_of_date",True,False,""),
"esg_ghg_carbon_disclosure":("GHG Carbon Disclosure (溫室氣體碳揭露)","","developer","esg-ghg-carbon-disclosure","as_of_date",True,False,""),
"company_industry_exposures":("公司產業曝險","relation","free","company-industry-exposures",None,False,True,""),
"company_peer_groups":("同業對照組","relation","free","company-peer-groups",None,False,True,""),
"industry_chain":("產業價值鏈成員","relation","starter","industry-chain","capture_date",False,True,"ticker|chain_name|node_name|capture_date"),
"subsidiary_investment":("轉投資/子公司","relation","developer","subsidiary-investment",None,False,True,"parent_ticker|invested_entity"),
"company_news":("Company News","","pro","company-news","published_at",False,False,""),
"mops_major_event":("重大訊息(結構化)","event","pro","mops-major-event","event_datetime",True,True,"ticker|event_date|event_time|source_group"),
"major_event_taxonomy":("重大訊息事件分類","event","pro","major-event-taxonomy","event_date",True,False,"ticker|event_date|event_time|subject"),
"attention_disposal_events":("注意/處置事件","event","pro","attention-disposal-events","event_date",False,True,""),
"day_trading_suspension":("當沖警示/暫停","event","pro","day-trading-suspension",None,False,True,""),
"margin_short_cover_date":("融券強制回補日","event","pro","margin-short-cover-date",None,False,True,"ticker|cover_date"),
"capital_formation_events":("資本形成事件(增/減資)","event","starter","capital-formation-events","event_date",True,False,"ticker|market|event_date|event_type"),
"investor_conference_calendar":("法人說明會行事曆","event","free","investor-conference-calendar","announcement_date",True,True,"ticker|market|conference_date"),
"stock_delisting_lifecycle":("Stock Delisting Lifecycle (下市生命週期)","","free","stock-delisting-lifecycle","announcement_date",False,False,""),
"stock_split_par_value_events":("Stock Split / Par Value Events (除權息 / 面額變動)","","free","stock-split-par-value-events",None,True,False,""),
"corporate_actions":("除權除息參考價 / Ex-Right & Ex-Dividend Reference Prices","","pro","corporate-actions","event_date",False,False,""),
"dividends":("股利與配息時程 / Dividends & Distribution Schedule","","pro","dividends","announcement_date",False,False,""),
"derivatives_market":("Derivatives Market (TAIFEX 期貨日)","","max","derivatives-market",None,True,False,""),
"futures_daily_context":("期貨日情境(基差/近月/法人OI)","derivatives","starter","futures-daily-context","trade_date",True,False,"contract|trade_date"),
"options_daily_taifex":("TAIFEX Options Daily (選擇權每日行情)","","max","options-daily-taifex","trade_date",True,False,""),
"taifex_options_settlement_price":("TAIFEX Options Settlement Price (選擇權每日結算價)","","max","taifex-options-settlement-price","trade_date",True,False,""),
"taifex_options_delta":("選擇權每日Delta","derivatives","max","taifex-options-delta","trade_date",True,False,"contract|call_put|contract_month_week|strike_price|trade_date"),
"taifex_put_call_ratio":("選擇權Put/Call Ratio","derivatives","max","taifex-put-call-ratio","trade_date",True,False,"trade_date"),
"taifex_atm_iv":("台指ATM隱含波動率","derivatives","max","taifex-atm-iv","trade_date",True,False,"trade_date"),
"taifex_final_settlement":("期交所最後結算價","derivatives","max","futures-final-settlement","settlement_date",True,False,"contract|settlement_date"),
"convertible_bond_overview":("可轉債總覽","derivatives","max","convertible-bond-overview","trade_date",True,False,"cb_id|trade_date"),
"convertible_bond_institutional":("可轉債法人買賣","derivatives","max","convertible-bond-institutional","trade_date",True,False,"cb_id|trade_date"),
"convertible_bond_monthly":("可轉債集保月報","derivatives","max","convertible-bond-monthly","data_month",True,True,"cb_id|data_month"),
"bond_yield_curve":("台灣公債殖利率曲線","macro","max","bond-yield-curve","trade_date",True,False,"tenor|trade_date"),
"interest_rate_snapshots":("Interest Rate Snapshots","","developer","interest-rate-snapshot","as_of_date",True,False,""),
"competitor_fx":("競貨幣匯率(JPY/KRW/CNY vs TWD)","macro","starter","competitor-fx","rate_date",True,False,"rate_date"),
"customs_trade_monthly":("海關進出口貿易統計","macro","starter","customs-trade-monthly","period_month",True,False,"stat_item|item_code|period_month"),
"export_orders_monthly":("外銷訂單金額(按貨品別)","macro","starter","export-orders-monthly","period_month",True,False,"stat_item|item_code|period_month"),
"production_value_index_monthly":("製造業生產價值指數","macro","starter","production-value-index-monthly","period_month",True,False,"stat_item|item_code|period_month"),
"macro_worldbank":("World Bank 總體指標","macro","developer","macro-worldbank","year",False,True,""),
"macro_global":("Global Macro","","enterprise","macro-global","trade_date",True,False,""),
}
