from typing import Any, Optional

class DatasetMethods:
    def attention_disposal_events(self, *, ticker: Optional[str] = None, start: Optional[str] = None, end: Optional[str] = None, as_of: Optional[str] = None, limit: Optional[int] = None, raw: bool = False, **extra: Any) -> Any: ...
    def balance_sheet(self, *, ticker: Optional[str] = None, start: Optional[str] = None, end: Optional[str] = None, as_of: Optional[str] = None, limit: Optional[int] = None, raw: bool = False, **extra: Any) -> Any: ...
    def block_trade_daily(self, *, start: Optional[str] = None, end: Optional[str] = None, as_of: Optional[str] = None, limit: Optional[int] = None, raw: bool = False, **extra: Any) -> Any: ...
    def bond_convertible_reference(self, *, ticker: Optional[str] = None, as_of: Optional[str] = None, limit: Optional[int] = None, raw: bool = False, **extra: Any) -> Any: ...
    def bond_yield_curve(self, *, start: Optional[str] = None, end: Optional[str] = None, as_of: Optional[str] = None, limit: Optional[int] = None, raw: bool = False, **extra: Any) -> Any: ...
    def broker_branch_reference(self, *, as_of: Optional[str] = None, limit: Optional[int] = None, raw: bool = False, **extra: Any) -> Any: ...
    def capital_formation_events(self, *, ticker: Optional[str] = None, start: Optional[str] = None, end: Optional[str] = None, as_of: Optional[str] = None, limit: Optional[int] = None, raw: bool = False, **extra: Any) -> Any: ...
    def cash_flow_statement(self, *, ticker: Optional[str] = None, start: Optional[str] = None, end: Optional[str] = None, as_of: Optional[str] = None, limit: Optional[int] = None, raw: bool = False, **extra: Any) -> Any: ...
    def company_industry_exposures(self, *, ticker: Optional[str] = None, limit: Optional[int] = None, raw: bool = False, **extra: Any) -> Any: ...
    def company_news(self, *, ticker: Optional[str] = None, start: Optional[str] = None, end: Optional[str] = None, as_of: Optional[str] = None, limit: Optional[int] = None, raw: bool = False, **extra: Any) -> Any: ...
    def company_peer_groups(self, *, ticker: Optional[str] = None, limit: Optional[int] = None, raw: bool = False, **extra: Any) -> Any: ...
    def competitor_fx(self, *, start: Optional[str] = None, end: Optional[str] = None, as_of: Optional[str] = None, limit: Optional[int] = None, raw: bool = False, **extra: Any) -> Any: ...
    def convertible_bond_institutional(self, *, ticker: Optional[str] = None, start: Optional[str] = None, end: Optional[str] = None, as_of: Optional[str] = None, limit: Optional[int] = None, raw: bool = False, **extra: Any) -> Any: ...
    def convertible_bond_monthly(self, *, ticker: Optional[str] = None, start: Optional[str] = None, as_of: Optional[str] = None, limit: Optional[int] = None, raw: bool = False, **extra: Any) -> Any: ...
    def convertible_bond_overview(self, *, ticker: Optional[str] = None, start: Optional[str] = None, end: Optional[str] = None, as_of: Optional[str] = None, limit: Optional[int] = None, raw: bool = False, **extra: Any) -> Any: ...
    def corporate_actions(self, *, ticker: Optional[str] = None, start: Optional[str] = None, end: Optional[str] = None, as_of: Optional[str] = None, limit: Optional[int] = None, raw: bool = False, **extra: Any) -> Any: ...
    def customs_trade_monthly(self, *, start: Optional[str] = None, end: Optional[str] = None, as_of: Optional[str] = None, limit: Optional[int] = None, raw: bool = False, **extra: Any) -> Any: ...
    def day_trading_suspension(self, *, ticker: Optional[str] = None, start: Optional[str] = None, end: Optional[str] = None, limit: Optional[int] = None, raw: bool = False, **extra: Any) -> Any: ...
    def derivatives_market(self, *, ticker: Optional[str] = None, start: Optional[str] = None, end: Optional[str] = None, as_of: Optional[str] = None, limit: Optional[int] = None, raw: bool = False, **extra: Any) -> Any: ...
    def dividends(self, *, ticker: Optional[str] = None, as_of: Optional[str] = None, limit: Optional[int] = None, raw: bool = False, **extra: Any) -> Any: ...
    def esg_ghg_carbon_disclosure(self, *, ticker: Optional[str] = None, as_of: Optional[str] = None, limit: Optional[int] = None, raw: bool = False, **extra: Any) -> Any: ...
    def etf_holdings(self, *, ticker: Optional[str] = None, as_of: Optional[str] = None, limit: Optional[int] = None, raw: bool = False, **extra: Any) -> Any: ...
    def export_orders_monthly(self, *, start: Optional[str] = None, end: Optional[str] = None, as_of: Optional[str] = None, limit: Optional[int] = None, raw: bool = False, **extra: Any) -> Any: ...
    def financial_ratios(self, *, ticker: Optional[str] = None, as_of: Optional[str] = None, limit: Optional[int] = None, raw: bool = False, **extra: Any) -> Any: ...
    def foreign_holding(self, *, ticker: Optional[str] = None, start: Optional[str] = None, end: Optional[str] = None, as_of: Optional[str] = None, limit: Optional[int] = None, raw: bool = False, **extra: Any) -> Any: ...
    def fund_etf_metadata(self, *, ticker: Optional[str] = None, as_of: Optional[str] = None, limit: Optional[int] = None, raw: bool = False, **extra: Any) -> Any: ...
    def futures_daily_context(self, *, ticker: Optional[str] = None, start: Optional[str] = None, end: Optional[str] = None, as_of: Optional[str] = None, limit: Optional[int] = None, raw: bool = False, **extra: Any) -> Any: ...
    def governance_t187ap33_l(self, *, ticker: Optional[str] = None, start: Optional[str] = None, end: Optional[str] = None, as_of: Optional[str] = None, limit: Optional[int] = None, raw: bool = False, **extra: Any) -> Any: ...
    def income_statement(self, *, ticker: Optional[str] = None, start: Optional[str] = None, end: Optional[str] = None, as_of: Optional[str] = None, limit: Optional[int] = None, raw: bool = False, **extra: Any) -> Any: ...
    def index_constituents(self, *, ticker: Optional[str] = None, start: Optional[str] = None, end: Optional[str] = None, as_of: Optional[str] = None, limit: Optional[int] = None, raw: bool = False, **extra: Any) -> Any: ...
    def industry_chain(self, *, as_of: Optional[str] = None, limit: Optional[int] = None, raw: bool = False, **extra: Any) -> Any: ...
    def industry_index(self, *, ticker: Optional[str] = None, as_of: Optional[str] = None, limit: Optional[int] = None, raw: bool = False, **extra: Any) -> Any: ...
    def industry_index_daily(self, *, start: Optional[str] = None, end: Optional[str] = None, as_of: Optional[str] = None, limit: Optional[int] = None, raw: bool = False, **extra: Any) -> Any: ...
    def institutional_flow(self, *, ticker: Optional[str] = None, start: Optional[str] = None, end: Optional[str] = None, as_of: Optional[str] = None, limit: Optional[int] = None, raw: bool = False, **extra: Any) -> Any: ...
    def interest_rate_snapshots(self, *, start: Optional[str] = None, end: Optional[str] = None, as_of: Optional[str] = None, limit: Optional[int] = None, raw: bool = False, **extra: Any) -> Any: ...
    def investor_conference_calendar(self, *, ticker: Optional[str] = None, start: Optional[str] = None, end: Optional[str] = None, as_of: Optional[str] = None, limit: Optional[int] = None, raw: bool = False, **extra: Any) -> Any: ...
    def issuer_classification(self, *, ticker: Optional[str] = None, as_of: Optional[str] = None, limit: Optional[int] = None, raw: bool = False, **extra: Any) -> Any: ...
    def issuer_profiles(self, *, ticker: Optional[str] = None, as_of: Optional[str] = None, limit: Optional[int] = None, raw: bool = False, **extra: Any) -> Any: ...
    def lending_utilization(self, *, ticker: Optional[str] = None, start: Optional[str] = None, end: Optional[str] = None, as_of: Optional[str] = None, limit: Optional[int] = None, raw: bool = False, **extra: Any) -> Any: ...
    def limit_events(self, *, start: Optional[str] = None, end: Optional[str] = None, as_of: Optional[str] = None, limit: Optional[int] = None, raw: bool = False, **extra: Any) -> Any: ...
    def macro_global(self, *, start: Optional[str] = None, end: Optional[str] = None, as_of: Optional[str] = None, limit: Optional[int] = None, raw: bool = False, **extra: Any) -> Any: ...
    def macro_worldbank(self, *, as_of: Optional[str] = None, limit: Optional[int] = None, raw: bool = False, **extra: Any) -> Any: ...
    def major_event_taxonomy(self, *, start: Optional[str] = None, end: Optional[str] = None, as_of: Optional[str] = None, limit: Optional[int] = None, raw: bool = False, **extra: Any) -> Any: ...
    def margin_short(self, *, ticker: Optional[str] = None, start: Optional[str] = None, end: Optional[str] = None, as_of: Optional[str] = None, limit: Optional[int] = None, raw: bool = False, **extra: Any) -> Any: ...
    def margin_short_cover_date(self, *, ticker: Optional[str] = None, start: Optional[str] = None, end: Optional[str] = None, limit: Optional[int] = None, raw: bool = False, **extra: Any) -> Any: ...
    def margin_short_total(self, *, start: Optional[str] = None, end: Optional[str] = None, limit: Optional[int] = None, raw: bool = False, **extra: Any) -> Any: ...
    def margin_system_stats(self, *, start: Optional[str] = None, end: Optional[str] = None, as_of: Optional[str] = None, limit: Optional[int] = None, raw: bool = False, **extra: Any) -> Any: ...
    def market_breadth(self, *, start: Optional[str] = None, end: Optional[str] = None, as_of: Optional[str] = None, limit: Optional[int] = None, raw: bool = False, **extra: Any) -> Any: ...
    def market_index(self, *, ticker: Optional[str] = None, start: Optional[str] = None, end: Optional[str] = None, as_of: Optional[str] = None, limit: Optional[int] = None, raw: bool = False, **extra: Any) -> Any: ...
    def market_overview_snapshots(self, *, start: Optional[str] = None, end: Optional[str] = None, as_of: Optional[str] = None, limit: Optional[int] = None, raw: bool = False, **extra: Any) -> Any: ...
    def market_value_weight(self, *, ticker: Optional[str] = None, start: Optional[str] = None, end: Optional[str] = None, as_of: Optional[str] = None, limit: Optional[int] = None, raw: bool = False, **extra: Any) -> Any: ...
    def monthly_revenue(self, *, ticker: Optional[str] = None, start: Optional[str] = None, end: Optional[str] = None, as_of: Optional[str] = None, limit: Optional[int] = None, raw: bool = False, **extra: Any) -> Any: ...
    def mops_major_event(self, *, ticker: Optional[str] = None, start: Optional[str] = None, end: Optional[str] = None, as_of: Optional[str] = None, limit: Optional[int] = None, raw: bool = False, **extra: Any) -> Any: ...
    def options_daily_taifex(self, *, start: Optional[str] = None, end: Optional[str] = None, as_of: Optional[str] = None, limit: Optional[int] = None, raw: bool = False, **extra: Any) -> Any: ...
    def price_enhanced(self, *, ticker: Optional[str] = None, start: Optional[str] = None, end: Optional[str] = None, limit: Optional[int] = None, raw: bool = False, **extra: Any) -> Any: ...
    def price_move_context(self, *, ticker: Optional[str] = None, start: Optional[str] = None, end: Optional[str] = None, as_of: Optional[str] = None, limit: Optional[int] = None, raw: bool = False, **extra: Any) -> Any: ...
    def production_value_index_monthly(self, *, start: Optional[str] = None, end: Optional[str] = None, as_of: Optional[str] = None, limit: Optional[int] = None, raw: bool = False, **extra: Any) -> Any: ...
    def return_index_daily(self, *, start: Optional[str] = None, end: Optional[str] = None, as_of: Optional[str] = None, limit: Optional[int] = None, raw: bool = False, **extra: Any) -> Any: ...
    def securities_firm_master(self, *, as_of: Optional[str] = None, limit: Optional[int] = None, raw: bool = False, **extra: Any) -> Any: ...
    def securities_lending(self, *, ticker: Optional[str] = None, start: Optional[str] = None, end: Optional[str] = None, as_of: Optional[str] = None, limit: Optional[int] = None, raw: bool = False, **extra: Any) -> Any: ...
    def security_master(self, *, ticker: Optional[str] = None, as_of: Optional[str] = None, limit: Optional[int] = None, raw: bool = False, **extra: Any) -> Any: ...
    def shareholding_concentration(self, *, ticker: Optional[str] = None, as_of: Optional[str] = None, limit: Optional[int] = None, raw: bool = False, **extra: Any) -> Any: ...
    def short_restriction_flags(self, *, start: Optional[str] = None, end: Optional[str] = None, as_of: Optional[str] = None, limit: Optional[int] = None, raw: bool = False, **extra: Any) -> Any: ...
    def short_sale_balance_control(self, *, ticker: Optional[str] = None, start: Optional[str] = None, end: Optional[str] = None, as_of: Optional[str] = None, limit: Optional[int] = None, raw: bool = False, **extra: Any) -> Any: ...
    def stock_delisting_lifecycle(self, *, start: Optional[str] = None, end: Optional[str] = None, as_of: Optional[str] = None, limit: Optional[int] = None, raw: bool = False, **extra: Any) -> Any: ...
    def stock_price_limit_daily(self, *, ticker: Optional[str] = None, start: Optional[str] = None, end: Optional[str] = None, as_of: Optional[str] = None, limit: Optional[int] = None, raw: bool = False, **extra: Any) -> Any: ...
    def stock_split_par_value_events(self, *, start: Optional[str] = None, end: Optional[str] = None, limit: Optional[int] = None, raw: bool = False, **extra: Any) -> Any: ...
    def subsidiary_investment(self, *, limit: Optional[int] = None, raw: bool = False, **extra: Any) -> Any: ...
    def taifex_atm_iv(self, *, start: Optional[str] = None, end: Optional[str] = None, as_of: Optional[str] = None, limit: Optional[int] = None, raw: bool = False, **extra: Any) -> Any: ...
    def taifex_final_settlement(self, *, ticker: Optional[str] = None, start: Optional[str] = None, end: Optional[str] = None, as_of: Optional[str] = None, limit: Optional[int] = None, raw: bool = False, **extra: Any) -> Any: ...
    def taifex_options_delta(self, *, ticker: Optional[str] = None, start: Optional[str] = None, end: Optional[str] = None, as_of: Optional[str] = None, limit: Optional[int] = None, raw: bool = False, **extra: Any) -> Any: ...
    def taifex_options_settlement_price(self, *, ticker: Optional[str] = None, start: Optional[str] = None, end: Optional[str] = None, as_of: Optional[str] = None, limit: Optional[int] = None, raw: bool = False, **extra: Any) -> Any: ...
    def taifex_put_call_ratio(self, *, start: Optional[str] = None, end: Optional[str] = None, as_of: Optional[str] = None, limit: Optional[int] = None, raw: bool = False, **extra: Any) -> Any: ...
    def tax_business_registration(self, *, as_of: Optional[str] = None, limit: Optional[int] = None, raw: bool = False, **extra: Any) -> Any: ...
    def technical_indicators(self, *, ticker: Optional[str] = None, start: Optional[str] = None, end: Optional[str] = None, as_of: Optional[str] = None, limit: Optional[int] = None, raw: bool = False, **extra: Any) -> Any: ...
    def tpex_daily_price(self, *, ticker: Optional[str] = None, start: Optional[str] = None, end: Optional[str] = None, as_of: Optional[str] = None, limit: Optional[int] = None, raw: bool = False, **extra: Any) -> Any: ...
    def trading_calendar(self, *, start: Optional[str] = None, end: Optional[str] = None, as_of: Optional[str] = None, limit: Optional[int] = None, raw: bool = False, **extra: Any) -> Any: ...
    def trading_rules_reference(self, *, as_of: Optional[str] = None, limit: Optional[int] = None, raw: bool = False, **extra: Any) -> Any: ...
    def twse_daily_price(self, *, ticker: Optional[str] = None, start: Optional[str] = None, end: Optional[str] = None, as_of: Optional[str] = None, limit: Optional[int] = None, raw: bool = False, **extra: Any) -> Any: ...
    def valuation_core_daily(self, *, ticker: Optional[str] = None, start: Optional[str] = None, end: Optional[str] = None, as_of: Optional[str] = None, limit: Optional[int] = None, raw: bool = False, **extra: Any) -> Any: ...
    def valuation_data(self, *, ticker: Optional[str] = None, start: Optional[str] = None, end: Optional[str] = None, as_of: Optional[str] = None, limit: Optional[int] = None, raw: bool = False, **extra: Any) -> Any: ...
    def warrants_reference(self, *, ticker: Optional[str] = None, as_of: Optional[str] = None, limit: Optional[int] = None, raw: bool = False, **extra: Any) -> Any: ...
