#!/usr/bin/env python3
"""Check the unverified compat mappings against real rows.

    python tools/verify_low_confidence.py                 # whatever needs no key
    TWMD_API_KEY=<restricted key> python tools/verify_low_confidence.py --all

Nine mappings in ``mapping/finmind_map.csv`` are graded ``low`` confidence:
plausible candidates that have never been compared against actual data, so the
compat layer refuses them rather than shipping a guess. Twenty-four more are
``medium``: mapped, but with field-level equivalence unconfirmed.

This fetches a sample from each candidate TWMD dataset and prints the columns it
actually returns, so the mapping can be confirmed or dropped on evidence. It
does not decide anything on its own -- promoting a mapping is a human judgement
recorded in ``tools/finmind_mapping_data.py``.

Two of the nine (warrants_reference, stock_delisting_lifecycle) are key-free, so
they can be settled right now; the rest wait for a restricted key.
"""
from __future__ import annotations

import argparse
import csv
import json
import os
import sys
import time
from typing import Any, Dict, List, Optional

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, ROOT)

MAP_CSV = os.path.join(ROOT, "mapping", "finmind_map.csv")
REPORT = os.path.join(ROOT, "mapping", "low_confidence_report.md")
DEMO_TICKER = "2330"
PACE_SECONDS = 3.0


def load_candidates(levels: List[str]) -> List[Dict[str, str]]:
    with open(MAP_CSV, encoding="utf-8") as fh:
        rows = list(csv.DictReader(fh))
    return [r for r in rows if r["confidence"] in levels and r["twmd_dataset"]]


def sample(client: Any, dataset: str) -> Dict[str, Any]:
    from twmd import registry
    from twmd.errors import TwmdError

    info = registry.get(dataset)
    kwargs: Dict[str, Any] = {"limit": 3, "raw": True}
    if info.entity_param:
        kwargs["ticker"] = DEMO_TICKER
    from twmd.envelope import extract_rows

    try:
        payload = client.dataset(dataset, **kwargs)
        rows, row_key = extract_rows(payload)
        # An entity-scoped query can legitimately return nothing -- warrants are
        # not indexed by the underlying stock's ticker, for one. Fall back to an
        # unfiltered sample so the columns are still observable.
        if not rows and "ticker" in kwargs:
            time.sleep(PACE_SECONDS)
            payload = client.dataset(dataset, limit=3, raw=True)
            rows, row_key = extract_rows(payload)
            if rows:
                return {"ok": True, "row_key": row_key, "row_count": len(rows),
                        "columns": sorted(rows[0]), "first_row": rows[0],
                        "note": "sampled without a ticker filter; %s returned no rows "
                                "for %s" % (dataset, DEMO_TICKER)}
    except TwmdError as exc:
        return {"ok": False, "error": "%s: %s" % (type(exc).__name__, exc)}
    return {
        "ok": True,
        "row_key": row_key,
        "row_count": len(rows),
        "columns": sorted(rows[0]) if rows else [],
        "first_row": rows[0] if rows else None,
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--all", action="store_true",
                        help="include medium-confidence mappings too")
    parser.add_argument("--pace", type=float, default=PACE_SECONDS)
    args = parser.parse_args()

    import twmd
    from twmd import registry

    levels = ["low", "medium"] if args.all else ["low"]
    candidates = load_candidates(levels)

    has_key = bool(os.environ.get("TWMD_API_KEY"))
    client = twmd.Client(max_concurrency=1)

    seen: Dict[str, Dict[str, Any]] = {}
    lines = [
        "# Unverified compat mappings — evidence report",
        "",
        "Generated by `tools/verify_low_confidence.py`. Each row shows the columns the",
        "candidate TWMD dataset actually returns, so a mapping can be confirmed or",
        "dropped on evidence rather than on plausibility.",
        "",
        "Promoting a mapping means editing `tools/finmind_mapping_data.py` and",
        "regenerating — this script never changes the grade by itself.",
        "",
        "| FinMind call | grade | confidence | TWMD dataset | tier | result |",
        "|---|---|---|---|---|---|",
    ]

    print("checking %d mapping(s)%s\n" % (len(candidates),
                                          "" if has_key else "  (no API key: key-gated ones will report 401)"))
    for row in candidates:
        for dataset in [d for d in row["twmd_dataset"].split("+") if d]:
            if dataset not in seen:
                info = registry.get(dataset)
                if info.free_tier_probe == "needs_key" and not has_key:
                    seen[dataset] = {"ok": False, "error": "needs an API key (not run)"}
                else:
                    seen[dataset] = sample(client, dataset)
                    time.sleep(args.pace)
            result = seen[dataset]
            info = registry.get(dataset)
            if result["ok"]:
                summary = "%d rows via `%s`; columns: %s" % (
                    result["row_count"], result["row_key"],
                    ", ".join("`%s`" % c for c in result["columns"][:10]) or "(none)")
            else:
                summary = result["error"]
            lines.append("| `%s` | %s | %s | `%s` | %s | %s |" % (
                row["finmind_method"] or "(via get_data)", row["mapping_tier"],
                row["confidence"], dataset, info.tier, summary))
            print("%-46s %-28s %s" % (row["finmind_method"], dataset,
                                      "ok" if result["ok"] else result["error"][:48]))
    client.close()

    resolved = sum(1 for v in seen.values() if v["ok"])
    lines += [
        "",
        "## Status",
        "",
        "- datasets sampled successfully: **%d / %d**" % (resolved, len(seen)),
        "- remaining blocked on a key: **%d**" % (len(seen) - resolved),
        "",
        "Full first rows: `mapping/low_confidence_samples.json`.",
    ]
    with open(REPORT, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines) + "\n")
    with open(os.path.join(ROOT, "mapping", "low_confidence_samples.json"),
              "w", encoding="utf-8") as fh:
        json.dump(seen, fh, ensure_ascii=False, indent=1, sort_keys=True, default=str)

    print("\nwrote %s (%d/%d datasets sampled)"
          % (os.path.relpath(REPORT, ROOT), resolved, len(seen)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
